# Generated by Django 2.1.7 on 2019-04-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana', '0002_auto_20190401_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='stokbarang',
            name='jml_dipinjam',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stokbarang',
            name='total_stok',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stokbarang',
            name='jml_keluar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stokbarang',
            name='jml_masuk',
            field=models.IntegerField(default=0),
        ),
    ]
