# Generated by Django 2.1.7 on 2019-04-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarana', '0003_auto_20190403_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangkeluar',
            name='penerima',
            field=models.CharField(max_length=50),
        ),
    ]
